# Glossary of terms

| Term         |                 Definition     |
|:-------------|:---------------------------------|
| by-subjects analysis ($F_1$) | An analysis where responses are averaged across items within each factor and subjects are the unit of analysis |
| by-items analysis ($F_2$)    | An analysis where responses are averaged across subjects within each factor and items are the unit of analysis |
| crossed random factors       | A design where there are two groups of random factors, such as subjects and items, and multiple subjects respond to multiple stimuli |
| data-generating process (DGP) | The equation approximating the process we assume to give rise to the data |
| fixed effect                 | An independent variable being measured or manipulated |
| intercept/grand mean         | The mean response across subjects and items |
| random effect                | A unit being sampled from a larger population that we want to generalize to |
| random intercept             | The subject or item's mean deviation from the grand mean |
| random slope                 | The subject or item's mean deviation from the mean fixed effect |
| variance components          | Parameters describing the distribution of random effects in the population |
